version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  verbosity: minimal
test: off
artifacts:
- path: src\MicroStationTagExplorer
- path: interop\Excel 2016
- path: interop\View V8i
- path: src\MicroStationTagExplorer\bin\AnyCPU\Release\MicroStationTagExplorer.exe
deploy: off